sudo: false

language: node_js
node_js: "14"

install:
  - npm install
  - export PATH="`pwd`/node_modules/.bin:$PATH"
  - elm-tooling install

script:
  - elm-make --yes
  - ./check.sh

cache:
  directories:
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts
    - examples/elm-stuff/build-artifacts
