sudo: false

language: node_js
node_js: "5.1"

install:
  - npm install -f elm@0.18.0 elm-test@0.18.4
  - export PATH="`pwd`/node_modules/.bin:$PATH"
  - (cd tests; elm-package install --yes)

script:
  - ./check.sh
